Feature build and push
ls1intum/team-allocator pull request #2
Opened 2023-04-14 03:11 UTC by Ayedrian

Only significant change to the script is the different "runs-on", the current Dockerfile uses an optimized Debian bullseye distro for Node

2023-04-17 17:04 UTC, Mtze requested changes

2023-04-19 07:29 UTC, Ayedrian commented on .github/workflows/build-and-push.yml
> +          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
For the dockerhub login, are the secrets the same or are they referred to differently such as DOCKERHUB_USERNAME etc.?

2023-04-19 11:41 UTC, Mtze commented on .github/workflows/build-and-push.yml
> +          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
The secrets names are fine.

2023-04-19 11:42 UTC, Ayedrian commented on .github/workflows/build-and-push.yml
> +          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
Nice, last commit seems to have produced a package.

2023-04-19 11:47 UTC, Mtze commented
For the future: Please use the suggestions in the PR - otherwise it is really hard and cumbersome to keep track about the changes.

2023-04-19 11:48 UTC, Mtze commented on .github/workflows/build-and-push.yml
> +  push:
I think you missed the `push` in your current version

2023-04-19 12:06 UTC, Ayedrian commented on .github/workflows/build-and-push.yml
> +  push:
Your suggested change was to remove it, no?

2023-04-19 12:07 UTC, Mtze commented on .github/workflows/build-and-push.yml
> +  push:
Have a close look at my suggestion...

2023-04-19 12:09 UTC, Ayedrian commented
> For the future: Please use the suggestions in the PR - otherwise it is really hard and cumbersome to keep track about the changes.

Is this just referring to the missing push?

2023-04-20 08:49 UTC, merged