Add examples for some components in the OpenAPI spec
ls1intum/team-allocator pull request #42
Opened 2023-05-25 11:39 UTC by Ayedrian

What changed: Some of the more complex and important components have examples now in accordance with their schemata: An example of a student object, skill object etc. were added.

Why the changes: We want to make the OpenAPI specification as easy to understand as possible, this will potentially help with testing and automatic code generation as well.

Testing steps: Not applicable.

2023-05-25 12:14 UTC, Mtze requested changes

2023-05-25 12:14 UTC, Mtze commented on docs/openapi_spec.yaml
> +          - { name: TYUR, id: sose24TYUR}
```suggestion
          - { name: Quartett, id: ios2223quartett}
          - { name: BSH, id: ios2223bsh}
```

2023-05-25 12:14 UTC, Mtze commented on docs/openapi_spec.yaml
> +        id: wise17ERT
```suggestion
      example:
        name: Quartett
        id: ios2223quartett
```

2023-05-26 09:12 UTC, Ayedrian commented on docs/openapi_spec.yaml
> +openapi: 3.1.0
Need version 3.1 to have support for adding descriptions of properties of a schema whose type is a `$ref` reference of another schema (without having to use the old `anyOf` keyword workaround), see [discussion](https://github.com/OAI/OpenAPI-Specification/issues/1514#issuecomment-1385551628).

2023-05-30 12:05 UTC, Mtze approved these changes

2023-05-30 12:05 UTC, merged